// <auto-generated />
using BeverageAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeverageAPI.Migrations
{
    [DbContext(typeof(BeverageContext))]
    [Migration("20241008191655_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BeverageAPI.Models.Beverage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Beverages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Refreshing lemon-lime soda",
                            Name = "Faxe Kondi",
                            Price = 15.99m,
                            Size = 6
                        },
                        new
                        {
                            Id = 2,
                            Description = "Classic Danish pilsner beer",
                            Name = "Ceres Top",
                            Price = 20.50m,
                            Size = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Light and crisp pilsner beer",
                            Name = "Royal Pilsner",
                            Price = 18.00m,
                            Size = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Strong lager with a rich taste",
                            Name = "Royal Export",
                            Price = 19.50m,
                            Size = 3
                        },
                        new
                        {
                            Id = 5,
                            Description = "Smooth, amber lager",
                            Name = "Royal Classic",
                            Price = 17.50m,
                            Size = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "Organic pilsner with a mild taste",
                            Name = "Royal Økologisk",
                            Price = 22.00m,
                            Size = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Energy drink with a lemon-lime flavor",
                            Name = "Faxe Kondi Booster",
                            Price = 12.99m,
                            Size = 5
                        },
                        new
                        {
                            Id = 8,
                            Description = "Sparkling water with a hint of citrus",
                            Name = "Egekilde Citrus",
                            Price = 10.00m,
                            Size = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "Sparkling water with elderflower taste",
                            Name = "Egekilde Elderflower",
                            Price = 10.00m,
                            Size = 1
                        },
                        new
                        {
                            Id = 10,
                            Description = "Full-bodied dark lager",
                            Name = "Albani Odense Classic",
                            Price = 18.50m,
                            Size = 2
                        },
                        new
                        {
                            Id = 11,
                            Description = "Strong beer with a distinct flavor",
                            Name = "Albani Giraf Beer",
                            Price = 24.00m,
                            Size = 4
                        },
                        new
                        {
                            Id = 12,
                            Description = "Hoppy IPA with tropical notes",
                            Name = "Albani Mosaic IPA",
                            Price = 25.00m,
                            Size = 2
                        },
                        new
                        {
                            Id = 13,
                            Description = "Sugar-free version of the classic soda",
                            Name = "Faxe Kondi Free",
                            Price = 15.99m,
                            Size = 5
                        },
                        new
                        {
                            Id = 14,
                            Description = "Sugar-free cola",
                            Name = "Pepsi Max",
                            Price = 16.50m,
                            Size = 6
                        },
                        new
                        {
                            Id = 15,
                            Description = "Rich, full-bodied lager",
                            Name = "Royal Beer",
                            Price = 18.99m,
                            Size = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
