// <auto-generated />
using BookAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookAPI.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20241006200334_AddedData")]
    partial class AddedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BookLibrary.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("longtext");

                    b.Property<string>("ISBN")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "J.D. Salinger",
                            ISBN = "9780316769488",
                            Price = 10.99m,
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            Id = 2,
                            Author = "George Orwell",
                            ISBN = "9780451524935",
                            Price = 9.99m,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Harper Lee",
                            ISBN = "9780060935467",
                            Price = 14.99m,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jane Austen",
                            ISBN = "9781503290563",
                            Price = 8.99m,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 5,
                            Author = "F. Scott Fitzgerald",
                            ISBN = "9780743273565",
                            Price = 10.29m,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Herman Melville",
                            ISBN = "9781503280786",
                            Price = 11.95m,
                            Title = "Moby-Dick"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Leo Tolstoy",
                            ISBN = "9781400079988",
                            Price = 12.99m,
                            Title = "War and Peace"
                        },
                        new
                        {
                            Id = 8,
                            Author = "J.R.R. Tolkien",
                            ISBN = "9780547928227",
                            Price = 13.49m,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Fyodor Dostoevsky",
                            ISBN = "9780486415871",
                            Price = 9.59m,
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            Id = 10,
                            Author = "J.R.R. Tolkien",
                            ISBN = "9780544003415",
                            Price = 24.99m,
                            Title = "The Lord of the Rings"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
