using Microsoft.EntityFrameworkCore;

namespace BookAPI.Data;

public class BookDbContext(DbContextOptions<BookDbContext> options) : DbContext(options)
{
    public DbSet<Book> Books { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<Book>(entity =>
        {
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedOnAdd(); // Configure the Id to be generated by the database
            entity.Property(e => e.Title).IsRequired();
        });

        //modelBuilder.Entity<Book>().HasData(
        //    new Book { Id = 1, Title = "The Catcher in the Rye", Author = "J.D. Salinger", Price = 10.99m, ISBN = "9780316769488" },
        //    new Book { Id = 2, Title = "1984", Author = "George Orwell", Price = 9.99m, ISBN = "9780451524935" },
        //    new Book { Id = 3, Title = "To Kill a Mockingbird", Author = "Harper Lee", Price = 14.99m, ISBN = "9780060935467" },
        //    new Book { Id = 4, Title = "Pride and Prejudice", Author = "Jane Austen", Price = 8.99m, ISBN = "9781503290563" },
        //    new Book { Id = 5, Title = "The Great Gatsby", Author = "F. Scott Fitzgerald", Price = 10.29m, ISBN = "9780743273565" },
        //    new Book { Id = 6, Title = "Moby-Dick", Author = "Herman Melville", Price = 11.95m, ISBN = "9781503280786" },
        //    new Book { Id = 7, Title = "War and Peace", Author = "Leo Tolstoy", Price = 12.99m, ISBN = "9781400079988" },
        //    new Book { Id = 8, Title = "The Hobbit", Author = "J.R.R. Tolkien", Price = 13.49m, ISBN = "9780547928227" },
        //    new Book { Id = 9, Title = "Crime and Punishment", Author = "Fyodor Dostoevsky", Price = 9.59m, ISBN = "9780486415871" },
        //    new Book { Id = 10, Title = "The Lord of the Rings", Author = "J.R.R. Tolkien", Price = 24.99m, ISBN = "9780544003415" }
        //);
    }
}
