using Microsoft.EntityFrameworkCore;

namespace BookAPI.Data;

public class BookDbContext(DbContextOptions<BookDbContext> options) : DbContext(options)
{
    public DbSet<Book> Books { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        // Replace with your actual MySQL connection string
        const string connectionString = "Server=localhost;Database=mybooklibrary;User=root;Password=mypassword;";

        optionsBuilder.UseMySql(connectionString, new MySqlServerVersion(new Version(8, 0, 21)));
    }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<Book>(entity =>
        {
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedOnAdd(); // Configure the Id to be generated by the database
            entity.Property(e => e.Title).IsRequired();
        });
    }
}
